name: pyramid_lint_example
description: Examples to demonstrate all the lints and fixes in pyramid_lint.
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.5.3
  pyramid_lint:
    path: ../
