name: pyramid_lint
description: >-
  Linting tool for Dart and Flutter projects to encourage good coding practices.
version: 1.1.0
repository: https://github.com/charlescyt/pyramid_lint
issue_tracker: https://github.com/charlescyt/pyramid_lint/issues
topics: [lints, analyzer]

screenshots:
  - description: >-
      Demonstration of the proper_super_init_state lint and its quick fix.
    path: resources/demo.gif

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=6.0.0 <7.0.0"
  analyzer_plugin: ^0.11.2
  collection: ^1.17.1
  custom_lint_builder: ^0.5.3
